#' Perform trend analyses on continous time series climate related data.
#'
#' @description Used to reevaluate the findings produced by trenda_dir() when
#' calc_infl_obs is set to FALSE. Should only be executed
#' after the function trenda_dir() was performed on data and influential observations
#' were determined. Also requires the ResTab csv file to work.
#' trenda_obs removes those influential observations and runs
#' the analysis again and places those findings
#'
#' @param data_dir Directory where data is stored. The function requires data to
#' be stored in a comma delimited csv file format and therefore only creates a
#' list of csv files from the specified folder.
#' @param log_trans logical. Set to TRUE if data is already log10-transformed.
#' If create_dir = TRUE a new folder named “_results_standard_log” will be created.
#' Observables will be transformed back to their original form and plots will be
#' adjusted for normal values.
#' @param res_tab_file result table of the same data generated by trenda;
#' needed for information about the influential observations which should be
#' left out in this analysis
#' @param calc_infl_obs logical; the influential observations should be
#' calculated again. Can be useful to turn off as this information is not
#' needed and sometimes the calculation of the influential observations for
#' GLS models does not work
#' @param create_dir logical. Creates a subfolder in the data_dir specified path if set to TRUE. Print to console if set to FALSE
#' If log_trans and calc_infl_obs is set to TRUE the following folders are created:
#'  “_results_standard”
#' “_results_standard_obs”
#' “_resulst_log”
#' “_results_log_obs”
#' @return the function does not return a value but stores the plot and table in
#' the assigned directories
#'
#' @details Since this function needs information about influential
#' observations, the function trenda has to be run first on the same
#' dataset.
#' @importFrom grDevices dev.off jpeg
#' @export
trenda_obs <- function(data_dir, log_trans = FALSE, create_dir = TRUE, res_tab_file,
                       calc_infl_obs = TRUE) {
  if (!log_trans) {
    dir.create(paste0(data_dir, Sys.Date(), "_results_standard_obs"))
    plot_dir <- paste0(data_dir, Sys.Date(), "_results_standard_obs/")
    result_name <- paste0(plot_dir, "result_rable_standard_obs_")
  } else {
    dir.create(paste0(data_dir, Sys.Date(), "_results_log_obs"))
    plot_dir <- paste0(data_dir, Sys.Date(), "_results_log_obs/")
    result_name <- paste0(plot_dir, "result_table_log_obs")
  }
  trend_files <- list.files(data_dir, pattern = "*.csv")

  ResTab <- data.frame(matrix(ncol = 13, nrow = 0))
  colnames(ResTab) <- c("File", "Index", "Beta0", "Beta1", "Beta2", "Phi1", "Phi2",
                        "Trend", "rSquared", "observations_to_remove_index",
                        "observations_to_remove_value",
                        "cooks_distance_of_observation",
                        "observations_to_remove_year"
  )

  # Import the table generated by the trenda function to exclude influential observations
  result_infl <- read.csv2(res_tab_file,
                           stringsAsFactors = FALSE)

  # since generalized Durbin-Watson-Test is random -> set seed
  set.seed(1)

  z <- 1

  output <- lapply(trend_files, function(trend_file) {

    print(sprintf("Data:----------%s", trend_file)) # Exceltitle

    ## read dataset
    dat <- read.csv2(sprintf("%s%s", data_dir, trend_file), header = TRUE, sep = ";", fileEncoding = "WINDOWS-1252")
    print(str(dat))
    f_r <- names(dat[1])
    ## dots have to be replaced in the variablenames for the plot function
    names(dat) <- gsub("\\.", "\\_", names(dat))

    ## all variables except for ID, Time and Jahr are environmental indicators
    varnames <- setdiff(names(dat), c("ID", "Time", f_r))

    ## ID is needed for the correlationstructure in the GLS-function
    dat$ID <- 1

    ## Time begins at 0
    dat["Time"] <- dat[1] - min(dat[1])

    for(varname in varnames){
      print(varname)

      # Remove observations which have been identified as influential in the previous
      # analysis
      # indices are saved as string, decimals are separated by comma
      index <- result_infl[result_infl$File == trend_file &
                             result_infl$Index == varname,
                           "observations_to_remove_index"]
      if (!is.na(index)) {
        index <- as.character(index)
        index <- strsplit(index, ",")
        index <- as.vector(sapply(index, as.numeric))
      }

      if (!is.list(index) && !is.na(index)) {
        # remove rows with NA since the index referes to influential observations
        temp_dat <- na.omit(dat[, c(f_r, "Time", "ID", varname)])
        temp_dat <- temp_dat[-index, ]

        print(str(temp_dat))

        ## calculate trend
        res <- compute_trend(temp_dat, varname, log_trans = log_trans,
                             calc_infl_obs = calc_infl_obs)

        ## save results
        ResTab[z,"File"] <<- trend_file
        ResTab[z,"Index"] <<- varname
        ResTab[z,"Beta0"] <<- round(as.numeric(res$beta[1]),4)
        ResTab[z,"Beta1"] <<- round(as.numeric(res$beta[2]),4)
        ResTab[z,"Beta2"] <<- round(as.numeric(res$beta[3]),4)
        ResTab[z,"Phi1"] <<- res$phi[1]
        ResTab[z,"Phi2"] <<- res$phi[2]
        ResTab[z,"Trend"] <<- res$trend
        ResTab[z,"rSquared"] <<- res$rsq

        ## save trend graphs
        if (log_trans) {
          name_file <- substr(trend_file, start = 6, stop = nchar(trend_file) - 4)
        } else {
          name_file <- suppressWarnings(abbreviate(trend_file, 8))
        }
        jpeg(filename = sprintf("%s%s_%s.jpeg", plot_dir,
                            name_file,
                            varname),
             width = 800, height = 800, quality = 640000)
        plot(res$plot)
        dev.off()
        z <<- z + 1
      }
    }
  })

  #summary(ResTab)
if (create_dir) {
  write.table(ResTab,
              paste0(result_name, format(Sys.Date(), "%Y-%m-%d"), ".csv"),
              sep = ";", dec = ",", row.names = FALSE, na = "")
} else {
  ResTab_Obs <- ResTab
  return(ResTab_Obs)
}
  print("----------------------DONE----------------------")
}
